version: '2'

services:
    api:
        build: .
        container_name: nfe.api
        environment:
            - DLL_PATH=bin/Debug/netcoreapp2.1
        ports:
            - "81:81"
        volumes:
            - /home/yreis/estudo/AspNetWebApi/Controllers:/app/Controllers
            - /home/yreis/estudo/AspNetWebApi/Core:/app/Core
            - /home/yreis/estudo/AspNetWebApi/Persistence:/app/Persistence
            - /home/yreis/estudo/AspNetWebApi/Properties:/app/Properties
            - /home/yreis/estudo/AspNetWebApi/Migrations:/app/Migrations
        networks:
            - dev_net

networks:
    dev_net:
        driver: bridge
        ipam:
            driver: default
            config:
            - subnet: 172.19.0.0/24
              gateway: 172.19.0.1
